replicaCount: 2

image:
  repository: 047723140817.dkr.ecr.ap-northeast-1.amazonaws.com/fastapi-app
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"